-- =============================================================================
-- 01_view_trade_vnd.sql — Analytical cube: trade values in VND
-- Schema: cube
--
-- Purpose:
--   Pre-joined view that exposes nds.trade_transaction with VND-converted
--   values for Power BI and downstream OLAP queries.
--
-- Business rule for FX join:
--   For each (year, month) trade grain, the exchange rate used is the rate
--   from the LAST available trading day in that month
--   (MAX(rate_date) WHERE rate_date <= last day of month).
--   This avoids mid-month rates on monthly aggregate trade data and aligns
--   with standard trade-statistics reporting practice.
--
-- vnd_per_usd source: nds.exchange_rate.vnd_per_usd = 1 / rate
--   where rate = 1 VND expressed in USD (from Frankfurter API base=VND).
--
-- trade_value_vnd = value (USD) * vnd_per_usd
--
-- Rows where no rate is available for a given month return NULL for
-- trade_value_vnd and fx_rate_date — they do NOT fail the view.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS cube;
